/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbproject;

/**
 *
 * @author abc
 */
public class DashboardEmp extends javax.swing.JFrame {
    
    int emp;
    boolean isMgr;
    
    public DashboardEmp(int emp) {
        initComponents();
        this.emp = emp;
        isMgr = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tasks = new javax.swing.JButton();
        generateSalary = new javax.swing.JButton();
        Attendance = new javax.swing.JButton();
        Sreport = new javax.swing.JButton();
        Profile = new javax.swing.JButton();
        star = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 45, 71));
        jPanel1.setPreferredSize(new java.awt.Dimension(730, 425));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 220, 40);

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DASHBOARD ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 220, 40);

        Tasks.setBackground(new java.awt.Color(105, 103, 115));
        Tasks.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        Tasks.setForeground(new java.awt.Color(255, 255, 255));
        Tasks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbproject/TaskAssignment.png"))); // NOI18N
        Tasks.setText("My Tasks");
        Tasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TasksActionPerformed(evt);
            }
        });
        jPanel1.add(Tasks);
        Tasks.setBounds(510, 120, 230, 100);

        generateSalary.setBackground(new java.awt.Color(105, 103, 115));
        generateSalary.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        generateSalary.setForeground(new java.awt.Color(255, 255, 255));
        generateSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbproject/PayGrade.png"))); // NOI18N
        generateSalary.setText("Generate Salary");
        generateSalary.setFocusPainted(false);
        generateSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateSalaryActionPerformed(evt);
            }
        });
        jPanel1.add(generateSalary);
        generateSalary.setBounds(510, 260, 230, 100);

        Attendance.setBackground(new java.awt.Color(105, 103, 115));
        Attendance.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        Attendance.setForeground(new java.awt.Color(255, 255, 255));
        Attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbproject/ComplaintPortal.png"))); // NOI18N
        Attendance.setText("Attendance Report");
        Attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendanceActionPerformed(evt);
            }
        });
        jPanel1.add(Attendance);
        Attendance.setBounds(270, 120, 230, 100);

        Sreport.setBackground(new java.awt.Color(105, 103, 115));
        Sreport.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        Sreport.setForeground(new java.awt.Color(255, 255, 255));
        Sreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbproject/SalaryReport.png"))); // NOI18N
        Sreport.setText("Salary Report");
        Sreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SreportActionPerformed(evt);
            }
        });
        jPanel1.add(Sreport);
        Sreport.setBounds(30, 260, 230, 100);

        Profile.setBackground(new java.awt.Color(105, 103, 115));
        Profile.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        Profile.setForeground(new java.awt.Color(255, 255, 255));
        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbproject/ViewProfile.png"))); // NOI18N
        Profile.setText("View Profile");
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });
        jPanel1.add(Profile);
        Profile.setBounds(30, 120, 230, 100);

        star.setBackground(new java.awt.Color(105, 103, 115));
        star.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        star.setForeground(new java.awt.Color(255, 255, 255));
        star.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbproject/EmpofMonth.png"))); // NOI18N
        star.setText("Star Employee");
        star.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starActionPerformed(evt);
            }
        });
        jPanel1.add(star);
        star.setBounds(270, 260, 230, 100);
        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(630, 320, 2, 2);

        jButton7.setText("Sign out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(660, 30, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TasksActionPerformed
        new Emp_Tasks(emp).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TasksActionPerformed

    private void generateSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateSalaryActionPerformed
        new Generate_Salary(emp, isMgr).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_generateSalaryActionPerformed

    private void AttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendanceActionPerformed
        new Emp_AttendanceView(emp, isMgr).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AttendanceActionPerformed

    private void SreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SreportActionPerformed
        new Employee_Salary(emp, isMgr).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SreportActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        new View_profile(emp, isMgr).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProfileActionPerformed

    private void starActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starActionPerformed
        new Star_Employee(emp).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_starActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);
        new MainPage().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardEmp(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attendance;
    private javax.swing.JButton Profile;
    private javax.swing.JButton Sreport;
    private javax.swing.JButton Tasks;
    private javax.swing.JButton generateSalary;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton star;
    // End of variables declaration//GEN-END:variables
}
