package dbproject;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Hp
 */
public class MainPage extends javax.swing.JFrame {

    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        login_admin = new javax.swing.JButton();
        login_emp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(47, 27, 71));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 45, 71));
        jPanel1.setLayout(null);

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Employee Management System");
        jPanel1.add(title);
        title.setBounds(60, 240, 710, 100);

        image.setBackground(new java.awt.Color(255, 255, 255));
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled design (4).png"))); // NOI18N
        jPanel1.add(image);
        image.setBounds(0, 40, 660, 250);

        login_admin.setBackground(new java.awt.Color(88, 84, 98));
        login_admin.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        login_admin.setForeground(new java.awt.Color(255, 255, 255));
        login_admin.setText("Login as Admin");
        login_admin.setFocusPainted(false);
        login_admin.setFocusable(false);
        login_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_adminMouseExited(evt);
            }
        });
        login_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_adminActionPerformed(evt);
            }
        });
        jPanel1.add(login_admin);
        login_admin.setBounds(390, 330, 160, 40);

        login_emp.setBackground(new java.awt.Color(88, 84, 98));
        login_emp.setFont(new java.awt.Font("Rockwell", 1, 13)); // NOI18N
        login_emp.setForeground(new java.awt.Color(255, 255, 255));
        login_emp.setText("Login as Employee");
        login_emp.setFocusPainted(false);
        login_emp.setFocusable(false);
        login_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_empMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_empMouseExited(evt);
            }
        });
        login_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_empActionPerformed(evt);
            }
        });
        jPanel1.add(login_emp);
        login_emp.setBounds(170, 330, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_adminActionPerformed
        try {
            // TODO add your handling code here:
            new AdminLogin().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_login_adminActionPerformed

    private void login_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_adminMouseEntered
        // TODO add your handling code here:
        //login_admin.setBackground(new java.awt.Color(105, 103, 115));
        login_admin.setBackground(new java.awt.Color(52, 45, 71));
    }//GEN-LAST:event_login_adminMouseEntered

    private void login_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_adminMouseExited
        // TODO add your handling code here:
        login_admin.setBackground(new java.awt.Color(88, 84, 98));
    }//GEN-LAST:event_login_adminMouseExited

    private void login_empMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_empMouseEntered
        // TODO add your handling code here:
        login_emp.setBackground(new java.awt.Color(52, 45, 71));
    }//GEN-LAST:event_login_empMouseEntered

    private void login_empMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_empMouseExited
        // TODO add your handling code here:
        login_emp.setBackground(new java.awt.Color(88, 84, 98));
    }//GEN-LAST:event_login_empMouseExited

    private void login_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_empActionPerformed
        new EmpLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_login_empActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_admin;
    private javax.swing.JButton login_emp;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
